### PR TITLE
4 param express handler

### LINKED ISSUE #7: Errors passed to next are not mapped
## Current

Express has a [built-in way for returning errors](https://expressjs.com/en/guide/error-handling.html) from any middleware with the `next(error)` call. It appears that errors returned this way do not get converted into `problem+json` because the handler is an ordinary middleware callback.

## Desired

Any error returned in the standard way should be intercepted and converted into a mapped problem document.

## Proposal

I think that following best practices of express, the 4-parameter error callback could be used instead. Thus the code can actually be simplified. Here's my implementation:

```ts
import { IMappingStrategy } from 'http-problem-details-mapper'

class HttpProblemResponseOptions {
  public strategy: IMappingStrategy;
}

export function HttpProblemResponse (options: HttpProblemResponseOptions) {
  const { strategy } = options

  return (err, req, res, next) => {
    let problem = strategy.map(err)

    res.statusCode = problem.status
    res.setHeader('Content-Type', 'application/problem+json')
    res.send(JSON.stringify(problem))
  }
}
```

The only difference is that it must be the last `app.use` call when setting up express

```diff
const server = express()
-server.use(HttpProblemResponse({strategy}))

server.get('/', async (req: express.Request, res: express.Response): Promise<any> => {
  return res.send(new NotFoundError({type: 'customer', id: '123' }))
})
+server.use(HttpProblemResponse({strategy}))
```

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #7

### CODE REVIEW

**Comment by AlexZeitler** [comment]
Thanks, 📦  `express-http-problem-details@0.1.2` has been released.

**Comment by AlexZeitler** [comment]
I'm just wondering if the release number should have been `0.2.0` after merging and releasing this PR?

At least thats how I understood the [FAQ](https://www.conventionalcommits.org/en/v1.0.0/#how-does-this-relate-to-semver):

> `fix` type commits should be translated to PATCH releases. `feat` type commits should be translated to MINOR releases. Commits with `BREAKING CHANGE` in the commits, regardless of type, should be translated to MAJOR releases.

Did I do something wrong?

**Comment by tpluscode** [comment]
Indeed it should have. I did not pay attention to that.

Did you pass any parameters to `standard-version`?

**Comment by AlexZeitler** [comment]
No, I just ran `yarn release`

**Comment by AlexZeitler** [comment]
Same happened for the other libs where we added `standard-version`

**Comment by tpluscode** [comment]
That is strange indeed. I've been using these tools for a few months now without such issues.

One thing though. Have you been squashing these PRs?

**Comment by AlexZeitler** [comment]
No I didn't squash them. So I should squash and use a conventional commit style message for it?

**Comment by tpluscode** [comment]
That is a choice. I asked because squashing essentially discard the original commits from history. So the `feat:` could get lost and thus distorting the result of `standard-version`.

**Comment by AlexZeitler** [comment]
Yes, that's why I did not squash until now. If I squash I would have to find the correct type of conventional commit `type` myself which imho would render usage of a tool like conventional commit /  `standard-version` sort of less useful.

**Comment by AlexZeitler** [comment]
Maybe I didn't read the manuals correctly but I didn't find something like "this is your workflow now"

**Comment by tpluscode** [comment]
>  If I squash I would have to find the correct type of conventional commit type myself which imho would render usage of a tool like conventional commit / standard-version sort of less useful.

Yes. I stopped squashing since I use conventional commits. And I pay much more attention to meaningful and cohesive commits. Before it was a mess.

> Maybe I didn't read the manuals correctly but I didn't find something like "this is your workflow now"

I don't follow

**Comment by AlexZeitler** [comment]
> > If I squash I would have to find the correct type of conventional commit type myself which imho would render usage of a tool like conventional commit / standard-version sort of less useful.
> 
> Yes. I stopped squashing since I use conventional commits. And I pay much more attention to meaningful and cohesive commits. Before it was a mess.
> 

So I should not have done it wrong here?

> > Maybe I didn't read the manuals correctly but I didn't find something like "this is your workflow now"
> 
> I don't follow

I mean: An example where the workflow using cc/sv is shown end to end.

**Pull request merged**
