### PR TITLE
docs: remove the step to add mapper implementation

### PR DESCRIPTION
**Pull request by tpluscode**
also added imports make it clear what is needed for the code

As a side note, I think it's rather redundant to include the instructions separate for JS and TS. They are virtually identical

### CODE REVIEW

**Comment by AlexZeitler** [comment]
Thanks for the feedback regarding JS/TS docs. I was thinking a lot about if this is necessary and just pushed both waiting for feedback like this. 

If you like, you can remove one of them. I tend to remove the TS version as JS is the lowest common denominator.

**Comment by AlexZeitler** [comment]
@tpluscode Do you want to remove the duplicate JS/TS parts or do you want me to merge the current state of the PR?

**Comment by tpluscode** [comment]
In a separate PR maybe

**Comment by AlexZeitler** [comment]
Thanks 📦 version `0.1.1` has been published on npm.

**Pull request merged**
